apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  selector:
    app: my-flask-app
  ports:
    - protocol: TCP
      port: 80         # Exposed port (external)
      targetPort: 5000  # The container's internal port
  type: LoadBalancer
